workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Create Flutter project structure
        script: |
          cd ..
          flutter create temp_app --org com.famaesmeralda --project-name fama_esmeralda_app
          cp -r temp_app/android fama_esmeralda_app/
          cp -r temp_app/ios fama_esmeralda_app/
          cd fama_esmeralda_app
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
